// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBekus0xpZKP4-5AKlFLlpS8KMD1TAr8tw',
    appId: '1:294700070447:web:88e4c3d8c5a906462fb8da',
    messagingSenderId: '294700070447',
    projectId: 'book-store-9db2f',
    authDomain: 'book-store-9db2f.firebaseapp.com',
    storageBucket: 'book-store-9db2f.firebasestorage.app',
    measurementId: 'G-BMXPQT056Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQaqAV1wVBVySbTpVNPQhMlq91-Ie4yPg',
    appId: '1:294700070447:android:1a2181c1fc662aff2fb8da',
    messagingSenderId: '294700070447',
    projectId: 'book-store-9db2f',
    storageBucket: 'book-store-9db2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT7lbqJAOVtJZTjZ9FiHFscd8-ynL48-M',
    appId: '1:294700070447:ios:ae357b88fab7792f2fb8da',
    messagingSenderId: '294700070447',
    projectId: 'book-store-9db2f',
    storageBucket: 'book-store-9db2f.firebasestorage.app',
    iosBundleId: 'com.example.bookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT7lbqJAOVtJZTjZ9FiHFscd8-ynL48-M',
    appId: '1:294700070447:ios:ae357b88fab7792f2fb8da',
    messagingSenderId: '294700070447',
    projectId: 'book-store-9db2f',
    storageBucket: 'book-store-9db2f.firebasestorage.app',
    iosBundleId: 'com.example.bookApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBekus0xpZKP4-5AKlFLlpS8KMD1TAr8tw',
    appId: '1:294700070447:web:821fb776789a1dd72fb8da',
    messagingSenderId: '294700070447',
    projectId: 'book-store-9db2f',
    authDomain: 'book-store-9db2f.firebaseapp.com',
    storageBucket: 'book-store-9db2f.firebasestorage.app',
    measurementId: 'G-BC7JVL3VPL',
  );

}